TOOL_ID = 24
SERVER_IP = "192.168.0.106"
SERVER_PORT = 5555
IMAGE_DIRECTORY = "/home/pi/Python/Pictures"
IMAGE_FORMAT = ".jpg"

#GPIO Pinouts
PIN_YELLOW = 18
PIN_GREEN = 16
PIN_RED = 23
PIN_BLUE = 21
PIN_LED = 24
#pins = {PIN_YELLOW:"PIN_YELLOW",PIN_GREEN:"PIN_GREEN",PIN_RED:"PIN_RED",PIN_BLUE:"PIN_BLUE"}